openapi: '3.0.2'
info:
  title: Sample To-do List App
  description: This is a sample server for a to-do list
  version: '1.0'

servers:
  - url: http://localhost:3000
    description: Development server
  - url: https://api.server.test/v1
    description: Staging server
  - url: https://api.server.prod/v1
    description: Production server

tags:
  - name: task
    description: Tasks operations

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          minimum: 1
        name:
          type: string
          maxLength: 25
        done:
          type: boolean
          example: false
    InternalServerError:
      type: object
      properties:
        statusCode:
          type: integer
          example: 500
        message:
          type: string
          example: 'Internal server error'
    BadRequestError:
      type: object
      properties:
        statusCode:
          type: integer
          example: 400
        message:
          type: array
          items:
            type: string
            example: 'name should not be empty'
        error:
          type: string
          example: 'Bad Request'
    NotFoundError:
      type: object
      properties:
        statusCode:
          type: integer
          example: 404
        message:
          type: string
          example: 'Not Found'

paths:
  /v1/task:
    get:
      tags:
        - task
      summary: Return all tasks.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    post:
      tags:
        - task
      summary: Add a task.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: 'remember the milk'
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: object
                    $ref: '#/components/schemas/Task'
        400:
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /v1/task/{id}:
    get:
      tags:
        - task
      summary: Details a task
      responses:
        200:
          description: Ok.
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: object
                    $ref: '#/components/schemas/Task'
        404:
          description: Not found task.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    put:
      tags:
        - task
      summary: Update a task.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: 'remember the milk and sugar'
      responses:
        204:
          description: No Content.
        400:
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    delete:
      tags:
        - task
      summary: Remove a task
      responses:
        204:
          description: No Content.
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    parameters:
      - name: id
        in: path
        description: ID of task to use
        required: true
        schema:
          type: integer
        style: simple
        example: 1
  /v1/task/{id}/done:
    patch:
      tags:
        - task
      summary: Complete a task
      responses:
        204:
          description: Done.
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    parameters:
      - name: id
        in: path
        description: ID of task to use
        required: true
        schema:
          type: integer
        style: simple
        example: 1
